#eureka.instance.preferIpAddress = true
#eureka.client.registerWithEureka = true
#eureka.client.fetchRegistry = true
#eureka.client.serviceUrl.defaultZone = http://localhost:8070/eureka

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka
