

server:
  port: 8073

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka





spring:
  security:
    oauth2:
      resourceserver:
        provider:
          keycloak:
            jwt:
              issuer-uri: http://localhost:8080/realms/spring-microservice



      zipkin:
        baseUrl: http://zipkin:9411
      sleuth:
        sampler:
          percentage: 1
      cloud:
        loadbalancer.ribbon.enabled: false
     
