

server:
  port: 8073

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka





spring:
  security:
    oauth2:
      resourceserver:
        provider:
          keycloak:
            jwt:
              jwk-set-uri: http://localhost:8080/auth/realms/spring-microservice
              issuer-uri: http://localhost:8080/realms/spring-microservice
              authorization-uri: http://localhost:8080/auth/realms/spring-microservice/protocol/openid-connect/auth
              token-uri: http://localhost:8080/auth/realms/spring-microservice/protocol/openid-connect/token
        client:
          registration:
            keycloak:
              scope: openid
              client-id: shop-gateway
              client-secret: QnxC5oWMzzfzxH9v9zSKIGCmeWvbX9pB
              authorization-grant-type: authorization_code


      zipkin:
        baseUrl: http://zipkin:9411
      sleuth:
        sampler:
          percentage: 1
      cloud:
        loadbalancer.ribbon.enabled: false
     
