

server:
  port: 8073

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka





spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: shop-gateway
            client-secret: QnxC5oWMzzfzxH9v9zSKIGCmeWvbX9pB
            clientName: shop-gateway
            authorization-grant-type: authorization_code
            redirectUri: 'http://localhost:8080/login/oauth2/code/shop-gateway'
            scope:
              - openid
              - profile
              - email
        provider:
          keycloak:
            authorization-uri: http://localhost:8080/realms/spring-microservices/protocol/openid-connect/auth
            user-info-uri: http://localhost:8080/realms/spring-microservices/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
            issuer-uri: http://localhost:8080/realms/spring-microservice
            jwk-set-uri: http://localhost:8080/realms/spring-microservices/protocol/openid-connect/certs
            token-uri: http://localhost:8080/realms/spring-microservice/protocol/openid-connect/token





      zipkin:
        baseUrl: http://zipkin:9411
      sleuth:
        sampler:
          percentage: 1
      cloud:
        loadbalancer.ribbon.enabled: false
     
